### ISSUE TITLE
NameError: global name 'convert' is not defined

### ISSUE THREAD

**Issue by rrezel** [riolet/SAM#7]
Traceback (most recent call last):
  File "import_paloalto.py", line 117, in <module>
    main(sys.argv)
  File "import_paloalto.py", line 109, in main
    import_file(argv[1])
  File "import_paloalto.py", line 68, in import_file
    translated_line = translate(line, lineNum);
  File "import_paloalto.py", line 53, in translate
    return (convert(*(split_data[7].split("."))),
NameError: global name 'convert' is not defined

**Comment by JoePelz** [comment]
The latest merge de6f009b105d923ebc8b3378d3580aba1c49ae3a should fix that

**Comment by JoePelz** [comment]
There's still a bug in preprocess.py...just a minute

**Comment by JoePelz** [comment]
fixed
